# traefik dynamic config for smart-flows service

http:
  middlewares:
    strip-airflow-api-prefix:
      stripPrefix:
        prefixes:
          - "/base/flows"
    strip-flows-db-api-prefix:
      stripPrefix:
        prefixes:
          - "/base/flows-db"
    # To Enable Cors
    airflow-cors:
      headers:
        accesscontrolallowmethods: "GET,OPTIONS,PUT,PATCH"
        accesscontrolallowheaders: "*"
        accesscontrolalloworiginlist: "*"
        accesscontrolmaxage: 100
        addvaryheader: true

  services:
    airflow-service:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME" }}-airflow-webserver:8080"
    flows-db-api-service:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME" }}-flows-postgrest:3000"
    airflow-api-service:
      loadBalancer:
        servers:
          - url: "http://{{ env "APP_NAME" }}-flows-api:80"

  routers:
    flows-db-api-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/flows-db`)"
      service: flows-db-api-service
      priority: 5
      middlewares:
        - strip-flows-db-api-prefix
        - airflow-cors

    airflow-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/airflow`)"
      service: airflow-service
      priority: 4
      middlewares:
        - airflow-cors

    airflow-api-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/flows`)"
      service: airflow-api-service
      priority: 3
      middlewares:
        - strip-airflow-api-prefix
        - airflow-cors
