# traefik dynamic config for smart-market service

http:
  services:
    smart-market:
      loadBalancer:
        servers:
          - url: "{{ env "APP_URL" }}:{{ env "SMART_MARKET_PORT" }}"

  routers:
    smart-market-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/`)"
      service: smart-market
      priority: 1
