# traefik dynamic config for smart-flows service

http:
  middlewares:
    strip-airflow-api-prefix:
      stripPrefix:
        prefixes:
          - "/base/flows"
    strip-flows-db-api-prefix:
      stripPrefix:
        prefixes:
          - "/base/flows-db"

  services:
    airflow-service:
      loadBalancer:
        servers:
          - url: {{ env "AIRFLOW_URL" }}
    flows-db-api-service:
      loadBalancer:
        servers:
          - url:  "{{ env "APP_URL" }}:{{ env "SMART_FLOWS_POSTGREST_PORT" }}"
    airflow-api-service:
      loadBalancer:
        servers:
          - url: "{{ env "APP_URL" }}:{{ env "SMART_FLOWS_API_PORT" }}"

  routers:
    flows-db-api-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/flows-db`)"
      service: flows-db-api-service
      priority: 5
      middlewares:
        - strip-flows-db-api-prefix

    airflow-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/airflow`)"
      service: airflow-service
      priority: 4

    airflow-api-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/base/flows`)"
      service: airflow-api-service
      priority: 3
      middlewares:
        - strip-airflow-api-prefix
